name: LLM4Band
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - scipy
  - tokenizers
  - transformers
  - torch
  - tqdm
  - datasets
  - accelerate
  - sentencepiece
  - safetensors
  - typing-extensions
  - protobuf
  - matplotlib
  - pytz
  - uvicorn
  - fastapi
  - grpc-cpp
  - libstdcxx-ng
  - libgcc-ng
  - zlib
  - nvidia-cublas-cu12
  - nvidia-cuda-runtime-cu12
  - nvidia-cudnn-cu12
  - nvidia-cufft-cu12
  - nvidia-curand-cu12
  - nvidia-cusolver-cu12
  - nvidia-cusparse-cu12
  - nvidia-nccl-cu12
  - xz
  - yaml
  - lz4-c
  - snappy
  - pip:
      - ray
      - cmake
      - typing-inspect
      - tqdm
      - huggingface-hub
      - wandb
      - fairscale
      - xformers
      - triton
      - uvloop
      - vllm
